### ISSUE TITLE
server: finish auth endpoints

### ISSUE THREAD

**Issue by stackdumper** [vladenego/almost_flerse#2]
### Register
- [x] hash password
- [x] validate email and password
- [x] sign and return auth token

### Login
- [x] validate email and password
- [x] sign and return auth token
- [x] compare with hashed password
- [x] extend test to cover multiple variants of input data

### Tests
- [x] test duplicate user registration
- [x] test with multiple variants of input email and password
- [x] test auth token validity

**Comment by vladenego** [comment]
Done
